---
title: "Biostat 212a Homework 2"
subtitle: "Due Feb 8, 2025 @ 11:59PM"
author: "Nathaniel Boyle and 006525153"
date: "`r format(Sys.time(), '%d %B, %Y')`"
format:
  html:
    theme: cosmo
    embed-resources: true
    number-sections: true
    toc: true
    toc-depth: 4
    toc-location: left
    code-fold: false
engine: knitr
knitr:
  opts_chunk: 
    fig.align: 'center'
    # fig.width: 6
    # fig.height: 4
    message: FALSE
    cache: false
---

## ISL Exercise 4.8.1 (10pts)

Using a little bit of algebra, prove that (4.2) is equivalent to (4.3). In
other words, the logistic function representation and logit representation for the logistic regression model are equivalent.

$$p(X) = \frac{e^{\beta_0 + \beta_1 X}}{1 + e^{\beta_0 + \beta_1 X}}$$

$$\frac{p(X)} {1 − p(X)} = eβ_0+β_1X$$
We have $p(X) = \frac{e^{\beta_0 + \beta_1 X}}{1 + e^{\beta_0 + \beta_1 X}}$ by definition
Thus,
$$ 1-p(X)= 1- \frac{e^{\beta_0 + \beta_1 X}}{1 + e^{\beta_0 + \beta_1 X}}$$
Simplify with common denominator

$$ 1- \frac{e^{\beta_0 + \beta_1 X}}{1 + e^{\beta_0 + \beta_1 X}} = \frac{1 + e^{\beta_0 + \beta_1 X}-e^{\beta_0 + \beta_1 X}}{1 + e^{\beta_0 + \beta_1 X}} = \frac{1}{1 + e^{\beta_0 + \beta_1 X}} = 1-p(X)$$
Therefore,
$$\frac{p(X)}{1-p(X)} = \frac{(1 + e^{\beta_0 + \beta_1 X})e^{\beta_0 + \beta_1 X}}{1 + e^{\beta_0 + \beta_1 X}}=e^{\beta_0 + \beta_1 X}$$
## ISL Exercise 4.8.6 (10pts)
Suppose we collect data for a group of students in a statistics class
with variables $X_1 = hours$ studied, $X_2 = undergrad GPA$, 
and Y =receive an A. We ft a logistic regression and produce estimated
coeffcient, $\hatβ_0 = −6$, $\hatβ_1 = 0.05$, $\hatβ_2 = 1$.

Estimate the probability that a student who studies for 40 h and
has an undergrad GPA of 3.5 gets an A in the class

From our logistic regression model we plug in our values to obtain a logit value:
$$logit(p) = \hatβ_0 + \hatβ_1X_1 +\hatβ_2X_2 = −6 + 0.05(40) + 1(3.5) = -0.5$$
Now we convert this logit value to a probablity:
$$ p = \frac{1}{1+e^{-logit(p)}} = \frac{1}{1+e^{0.5}} ≈ 0.378 $$
This means our student in this case has a roughly 37.8% chance of getting an A.

How many hours would the student in part (a) need to study to
have a 50 % chance of getting an A in the class?

A 50% chance is equivalent to $logit(p)=0$ thus we can solve for X, the
amount of hours we study for:

$$0 = −6 + 0.05(X) + 1(3.5)$$
$$\frac{6-3.5}{0.05} = X = 50$$
Thus a student with a gpa of 3.5 would need 50 hours of studying for a 50% chance
to get an A, according to this logistic model.

## ISL Exercise 4.8.9 (10pts)

This problem has to do with odds.
(a) On average, what fraction of people with an odds of 0.37 of
defaulting on their credit card payment will in fact default?
(b) Suppose that an individual has a 16 % chance of defaulting on
her credit card payment. What are the odds that she will default?

## ISL Exercise 4.8.13 (a)-(i) (50pts)

## Bonus question: ISL Exercise 4.8.13 Part (j) (30pts)

## Bonus question: ISL Exercise 4.8.4 (30pts)
